---
# https://taskfile.dev

version: '3'

dotenv:
  - '.env'
  - '.env_local'

tasks:

  lint:
    desc: Lint Dockerfile with hadolint
    cmds:
      - hadolint Dockerfile

  build:
    deps:
      - lint
    desc: Build Docker image
    cmds:
      - docker build
               --memory=8g --cpus=8
               --build-arg 'ROOT_DIR={{ .ROOT_DIR }}'
               --build-arg 'HTTP_PORT={{ .HTTP_PORT }}'
               --build-arg 'DEBUG={{ .DEBUG }}'
               --tag '{{ .IMAGE_NAME }}'
               --file Dockerfile
               .

  publish:
    desc: Publish Docker image
    cmds:
      - docker tag '{{ .IMAGE_NAME }}'
                   '{{ .DOCKER_HUB_NAMESPACE }}/{{ .IMAGE_NAME }}:latest'
      - docker push '{{ .DOCKER_HUB_NAMESPACE }}/{{ .IMAGE_NAME }}:latest'

  start:
    desc: Start Docker container
    cmds:
      - docker run --rm -d
                   --network host
                   -v 'pxe-tftpboot:{{ .ROOT_DIR }}/'
                   --name '{{ .CONTAINER_NAME }}'
                   '{{ .IMAGE_NAME }}'

  stop:
    desc: Stop Docker container
    cmds:
      - docker stop '{{ .CONTAINER_NAME }}'

  exec:
    desc: Execute shell inside container
    cmds:
      - docker exec -it '{{ .CONTAINER_NAME }}' /bin/sh

  logs:
    desc: Show container logs
    cmds:
      - docker logs '{{ .CONTAINER_NAME }}'

...
